### PR TITLE
创建Object分行排列时逗号前置

### PR DESCRIPTION
**Pull request by nfang**
觉得创建Object分行排列时逗号前置较好，这样不管key和value多长，逗号总是对齐的，便于发现missing comma。例子可以参见一些node框架，如express, socketio, mongoose等。

### CODE REVIEW

**Comment by windyrobin** [comment]
First forgive me that comment this issue so late ,but I really have some trivial things to tackle ...

I admit that if we put ',' ahead of one line ,it will help us avoid some mistakes,
but at the same time , this style wasn't so elegant and would cause reading flow interrupted by the  ','  symbol...

you could take this file https://github.com/joyent/node/blob/master/lib/http.js#L147 for referrence

**Comment by nfang** [comment]
Well, if u say so. In the example mentioned, status codes are all fix length string and the messages can perfectly fit into a single line. In that case, the place to put comma, actually, doesn't matter too much. But when we have a property whose value is an object literal or an array, I believe it would be easier to detect missing commas if we put them ahead.

Anyway, I guess it's safe to conclude that this issue is more of a personal preference and depends on specific scenario.

**Comment by windyrobin** [comment]
yes ，I think it could be a personal preference ,but not a standard guideline

besides that ，your blog is really very good ...

**Comment by nfang** [comment]
thx for ur visit :)

**Pull request closed without merging**
